### ISSUE TITLE
More information about the objects

### ISSUE THREAD

**Issue by StoicGilgamesh** [opipari/ClearPose#1]
First of all Amazing work and Dataset! Extremely helpful for a very niche and novel topic within computer vision.

I am myself working on the topic of transparent objects. I went through the paper and this repository and have a few questions:

1) Is it possible to know what is the material for each object in the dataset?
2) Is it possible to know what is the Index of Refraction (I.O.R) for each object in the dataset?

It would be immensely helpful if you can provide this information.

Best Regards.

**Comment by cxt98** [comment]
Thanks for your interest on the Clearpose dataset. We updated the material of objects as either plastic or glass in readme. Currently we do not have the device to measure precise index of refraction of objects, and we may provide that later. You may use the empirical values of the materials temporarily. We also welcome suggestions on measuring ior accurately.

**Comment by opipari** [comment]
Thanks for your interest in ClearPose. We'll reopen this issue if we find a way to measure the index of refraction.

**Comment by StoicGilgamesh** [comment]
Thank you guys!
