### ISSUE TITLE
关于数据集中数据处理的一些问题

### ISSUE THREAD

**Issue by Gaben21** [opipari/ClearPose#7]
@cxt98 @huijieZH 
非常感谢你们的工作，对我有着很大的帮助。现在我想按照你们的方法制作一个新的数据集，有一些问题想要请教一下你们：
1、使用realsense相机采集图像的时候，是手持相机绕着物体进行拍摄，然后间隔一定的时间采样rgb图片和原始深度图片吗？
2、数据集中recon文件夹的内容包括object_pose、camera_pose、camera_label等是在标注之前就需要记录好的还是说这是在使用ProgressLabeller处理之后得到的结果
3、在label object步骤之后，如何输出调整后的深度图像以及表面法线图像呢？如果方便的话，可以提供相关代码吗

**Comment by cxt98** [comment]
1. 是的，我们发现robot拿相机有时候移动太快图片会模糊，并且物体经常照不全；另外我们的标注方法assume物体在过程中不能移动，所以也没有用转台之类的工具
2. 处理过的，在采集完数据之后会跑一遍orbslam3计算出camera的轨迹，然后在blender里用我们的插件标一遍物体的pose，之后就是一个pose乘法就能算出每一帧物体在camera frame下的pose了
3. 我们是利用物体model render出的depth，renderer是blender内置的，normal再根据depth取微分计算。代码在这：https://github.com/huijieZH/ProgressLabeller/blob/bc8e91801e7d42aa5d1cf6a5d373df3ba5b0ff65/offline/render.py#L381

**Comment by Gaben21** [comment]
好的，非常的感谢
